### ISSUE TITLE
Numpy installation: failed to map segment from shared object

### ISSUE THREAD

**Issue by cloudmountofficial** [trampgeek/jobeinabox#4]
Hi!

I ran into the following error while trying to `import numpy`. `import numpy` works inside the python3 interactive session from cli inside the docker. Might be related to [this issue](https://github.com/numpy/numpy/issues/14148) ?

Error:
```
***Error***
Traceback (most recent call last):
  File "__tester__.python3", line 1, in <module>
    import numpy as np
  File "/usr/local/lib/python3.6/dist-packages/numpy/__init__.py", line 152, in <module>
    from . import random
  File "/usr/local/lib/python3.6/dist-packages/numpy/random/__init__.py", line 181, in <module>
    from . import _pickle
  File "/usr/local/lib/python3.6/dist-packages/numpy/random/_pickle.py", line 1, in <module>
    from .mtrand import RandomState
  File "_bit_generator.pxd", line 14, in init numpy.random.mtrand
ImportError: /usr/local/lib/python3.6/dist-packages/numpy/random/_bit_generator.cpython-36m-x86_64-linux-gnu.so: failed to map segment from shared object
```

**Comment by trampgeek** [comment]
This is probably just a memory error. See for example [this CodeRunner thread](https://coderunner.org.nz/mod/forum/discuss.php?d=150&lang=de). If you're using Jobe from CodeRunner, customise the question, expand the _Advanced _Customisation_ panel and set a much larger memory limit (or use 0 in the first instance, which turns off memory limits). If you're using Jobe from the raw REST API, add a memlimit parameter to the request - see examples in testsubmit.py, e.g. when running Octave.

**Comment by cloudmountofficial** [comment]
Thanks for the help. Yep, it turned out to be a memory error. Works fine when I set the limit to 0.
